language: java

jdk:
  - oraclejdk8

sudo: true

before_install:
  - sudo service mysql stop
  - sudo service postgresql stop
  - sudo service acpid stop
  - sudo service atd stop
  - sudo service cron stop
  - sudo service memcached stop
  - sudo service ntp stop
  - sudo service rabbitmq-server stop
  - sudo service resolvconf stop
  - sudo service sshguard stop
  - sudo service ssh stop
  - sudo service rsyslog stop
  - openssl aes-256-cbc -K $encrypted_a349a4fa8af7_key -iv $encrypted_a349a4fa8af7_iv -in settings.tar.enc -out settings.tar -d && tar -xf settings.tar && cat known_hosts >> ~/.ssh/known_hosts
 
cache:
    directories:
      - $HOME/.m2

script: mvn -s ./settings.xml deploy -Dexternal -DtrimStackTrace=false ; else mvn verify -DtrimStackTrace=false